<?php
include_once $_SERVER['DOCUMENT_ROOT'] . '/init.php';

$title             = 'Data Services';
$active_parent     = 'Airlines';
$active_page_title = 'Data Services';

$extra_styles = <<<EOF
    #data-services li {
        margin: 20px 0;
    }
    #data-services li img {
        margin-right: 20px;
    }
    #data-services li div {
        width: 840px;
    }
    #data-services > li:last-child {
        margin-bottom: 0;
    }
EOF;

include_once WEB_ROOT . '/templates/head.php';

?>
<section>
    <h1>Data Services</h1>
    <ul id="data-services">
        <li class="clearafter">
            <img src="<?= BASE_URL; ?>static/images/data-services-1.png" width="100" class="float-left">
            <div class="float-left">
                <strong>AIRCRAFT DEPARTURES AND DELAY MANAGEMENT</strong><br>
                Gathers and displays real-time progress information to pilots and airport operations personnel of all pre-departure processes, (baggage loading, passenger boarding, catering, fueling, etc.) to better ensure on-time aircraft departures.
            </div>
        </li>
        <li class="clearafter">
            <img src="<?= BASE_URL; ?>static/images/data-services-2.png" width="100" class="float-left">
            <div class="float-left">
                <strong>AIRCRAFT WEATHER REPORTING</strong><br>
                Gathers available atmospheric observations from onboard the airplane as it travels around the globe, sending a steady transmission of data to the ground for use by AOCs and outside weather providers.
            </div>
        </li>
        <li class="clearafter">
            <img src="<?= BASE_URL; ?>static/images/data-services-3.png" width="100" class="float-left">
            <div class="float-left">
                <strong>FLIGHT TRACKER</strong><br>
                Provides aircraft position regardless of radar contact or jurisdiction of airspace. Data captured will include a variety of metrics for both a real-time display and post flight data analysis.
            </div>
        </li>
        <li class="clearafter">
            <img src="<?= BASE_URL; ?>static/images/data-services-4.png" width="100" class="float-left">
            <div class="float-left">
                <strong>FOQA DATA STREAMING</strong><br>
                Allows airlines to automatically capture, analyze and visualize data generated by an aircraft while in flight. Data collected is used by airlines to analyze performance, identify trends, investigate minor incidents, and review procedural and regulatory compliance.
            </div>
        </li>
    </ul>
</section>
<?php

include_once WEB_ROOT . '/templates/foot.php';